name = "Cobbleblock"
author = "LucyAzalea"
version = "0.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84c754d0586921294201e7d157d3e49841e95234b5a8b48d1e13df2cfcb3f910"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.221"

[options]
datapack-folder = "global_packs/required_data"
