name = "Cobbleblock"
author = "LucyAzalea"
version = "0.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b787bf42c9a2d1eae10197d81555dfbb0b51cff57e2d7fa2c5c903b8dfe3d8c7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.221"

[options]
datapack-folder = "global_packs/required_data"
