name = "Cobbleblock"
author = "LucyAzalea"
version = "0.1.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8eb2b2ec5e5a5d3ba9c6130670742569e58f0b3f5759baac3d3300d06229012"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
