accepts-transfers=false
allow-flight=false
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
difficulty=normal
enable-command-block=true
enable-jmx-monitoring=false
enable-query=false
enable-rcon=true
enable-status=true
enforce-secure-profile=true
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=false
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla,fabric,accessories,balm,beautify,carved_wood,cobblecuisine,cobbledollars,cobblefurnies,cobblemon,cobblemon-additions,cobblemonbattlepositions,cobblemonraiddens,cobblenav,cobbleversebadges,cobbreeding,comforts,cozyhome,fabric-convention-tags-v2,fightorflight,handcrafted,legendarymonuments,lenientdeath,libjf-data-v0,lumymon,mega_showdown,moarconcrete,mr_cobblemon_journeymounts,obc,pokeblocks,porting_lib_item_abilities,rctmod,rechiseled,repurposed_structures,server_translations_api,sophisticatedbackpacks,sophisticatedcore,sophisticatedstorage,supermartijn642corelib,tim_core,tmcraft,toms_storage,trinkets,vanillabackport,waystones,zamega,lumymon\:compat,carved_wood\:carvedwood_vanillabackport_compat,cobblemon\:repurposedstructurescobblemon
level-name=world
level-seed=
level-type=skyblockbuilder\:skyblock
log-ips=true
max-chained-neighbor-updates=1000000
max-players=20
max-tick-time=60000
max-world-size=29999984
motd=A Cobbleblock Minecraft Server
network-compression-threshold=256
online-mode=true
op-permission-level=4
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
query.port=25565
rate-limit=0
rcon.password=
rcon.port=25575
region-file-compression=deflate
require-resource-pack=false
resource-pack=
resource-pack-id=
resource-pack-prompt=
resource-pack-sha1=
server-ip=
server-port=25565
simulation-distance=10
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=16
sync-chunk-writes=true
text-filtering-config=
use-native-transport=true
view-distance=10
white-list=true
